name: Dart # Name of the Action

on:
  pull_request:
    branches: ["main"] # Defining that it will only run on the pull request on the main branch

jobs:
  build:
    runs-on: ubuntu-latest # GitLab has 3 operating systems to run your app in and we will be using ubuntu for that purpose.

    defaults:
      run:
        working-directory: widgets # Defining the commands to run in the specific directory since the flutter project is in those libraries

    steps:
      - uses: actions/checkout@v3 # this command is used to check out (clone) the source code repository into the runner's workspace.

      # Note: This workflow uses the latest stable version of the Flutter SDK.
      # Installing Flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable" # or: 'beta', 'dev' or 'master'

      # Consider passing '--fatal-infos' for slightly stricter analysis.
      - name: Analyze project source
        run: flutter analyze

      #This is to verify formating in the dart code
      - name: Run Format
        run: dart format .

      # Your project will need to have tests in test/ and a dependency on
      # package:test for this step to succeed. Note that Flutter projects will
      # want to change this to 'flutter test'.
      # - name: Run tests
      #   run: flutter test
