name: Publish to pub.dev

on:
  # pull_request:
  #   branches: ["main"]
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*"

jobs:
  publish:
    permissions:
      id-token: write # Required for authentication using OIDC
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
    with:
      # Specify the github actions deployment environment
      environment: pub.dev

    # with:
    #   working-directory: path/to/package/within/repository

    # runs-on: ubuntu-latest
    # steps:
    # - uses: actions/checkout@v2
    #   with:
    #     fetch-depth: 0
